### ISSUE TITLE
Using --input video file

### ISSUE THREAD

**Issue by BTakacs-Oxit** [JimWest/MeFaMo#18]

**Comment by Qaanaaq** [comment]
Hello, unfortunately I also was not able to use an input video file for some reason.  Was also trying the --input <filelocation> way but did not seem to work.

**Comment by redbean** [comment]
in my case I change the line 133 in mefamo.py like below
cap = cv2.VideoCapture(input)#, cv2.CAP_DSHOW)  

when the video is given in path, cv2.videocapture with cv2.CAP_DSHOW returns None.

**Comment by fuselayer** [comment]
> in my case I change the line 133 in mefamo.py like below cap = cv2.VideoCapture(input)#, cv2.CAP_DSHOW)
> 
> when the video is given in path, cv2.videocapture with cv2.CAP_DSHOW returns None.

Tried this, but getting a slightly different error at the exact same line. 

![image](https://github.com/JimWest/MeFaMo/assets/145614503/c0fb9b0d-3a05-4e71-af80-8b84ed207cc1)

Starting MeFaMo
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "C:\Users\Main\MeFaMo\examples\mefamo_cli.py", line 22, in <module>
    mediapipe_face.start()
  File "C:\Users\Main\MeFaMo\venv\lib\site-packages\mefamo_mediapipefacemocap-0.1-py3.10.egg\mefamo\mefamo.py", line 133, in start
    cap = cv2.VideoCapture(input)#, cv2.CAP_DSHOW)
UnboundLocalError: local variable 'input' referenced before assignment
